-- CUPADM.CAT_ESTATUS_HOMOLOGA definition

--
-- CAT_ESTATUS_HOMOLOGA  (Table) 
--
CREATE TABLE CUPADM.CAT_ESTATUS_HOMOLOGA
(
  ID_ESTATUS_HOMOLOGA  NUMBER(38)               NOT NULL,
  ESTATUS_HOMOLOGA     VARCHAR2(30 BYTE)        NOT NULL
)
TABLESPACE CUP_DATA01
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN CUPADM.CAT_ESTATUS_HOMOLOGA.ID_ESTATUS_HOMOLOGA IS 'Clave única del estatus Homologa';

COMMENT ON COLUMN CUPADM.CAT_ESTATUS_HOMOLOGA.ESTATUS_HOMOLOGA IS 'estatus homologa';



--
-- CAT_ESTATUS_HOMOLOGA_PK  (Index) 
--
CREATE UNIQUE INDEX CUPADM.CAT_ESTATUS_HOMOLOGA_PK ON CUPADM.CAT_ESTATUS_HOMOLOGA
(ID_ESTATUS_HOMOLOGA)
LOGGING
TABLESPACE CUP_DATA01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM CUPAPP.CAT_ESTATUS_HOMOLOGA;

--
-- CAT_ESTATUS_HOMOLOGA  (Synonym) 
--
CREATE OR REPLACE SYNONYM CUPAPP.CAT_ESTATUS_HOMOLOGA FOR CUPADM.CAT_ESTATUS_HOMOLOGA;


-- 
-- Non Foreign Key Constraints for Table CAT_ESTATUS_HOMOLOGA 
-- 
ALTER TABLE CUPADM.CAT_ESTATUS_HOMOLOGA ADD (
  CONSTRAINT CAT_ESTATUS_HOMOLOGA_PK
  PRIMARY KEY
  (ID_ESTATUS_HOMOLOGA)
  USING INDEX CUPADM.CAT_ESTATUS_HOMOLOGA_PK);

--GRANT
GRANT INSERT, SELECT, UPDATE ON CUPADM.CAT_ESTATUS_HOMOLOGA TO CUPAPP;
