ALTER TABLE CUPADM.CUP_BIT_HOMOLOGA_FECHAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUPADM.CUP_BIT_HOMOLOGA_FECHAS CASCADE CONSTRAINTS;

--
-- CUP_BIT_HOMOLOGA_FECHAS  (Table) 
--
CREATE TABLE CUPADM.CUP_BIT_HOMOLOGA_FECHAS
(
  ID_EMISION_SF        NUMBER(10)               NOT NULL,
  FECHA_EVALUACION_CB  DATE,
  FECHA_EVALUACION_ED  DATE,
  FECHA_PROCESO        DATE                     DEFAULT SYSDATE               NOT NULL,
  FECHA_ECCC           DATE,
  ID_ESTATUS_HOMOLOGA  NUMBER(38)               DEFAULT 1                     NOT NULL,
  ACTIVAR_CUP          NUMBER(38),
  USUARIO              VARCHAR2(15 BYTE)        DEFAULT 'SISTEMAS'
)
TABLESPACE CUP_DATA01
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.ID_EMISION_SF IS 'Campo llave de la tabla Emision_SF';
COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.FECHA_EVALUACION_CB IS 'Fecha anterior de evaluacion de la tablaCompetencias_basicas';
COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.FECHA_EVALUACION_ED IS 'Fecha anterior de evaluacion de la tabla Evaluacion Desempeño';
COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.FECHA_PROCESO IS 'Fecha en que se ejecuto la homologación';
COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.FECHA_ECCC IS 'Fecha de la tabla del ECCC';
COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.ID_ESTATUS_HOMOLOGA IS 'Clave única del catálogo de estatus Homologa';
COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.ACTIVAR_CUP IS 'Se Modifico el CUP?, 1=SI, 0=NO';
COMMENT ON COLUMN CUPADM.CUP_BIT_HOMOLOGA_FECHAS.USUARIO IS 'Clave del usuario que ejecuto el proceso';



--
-- CUP_PK_BIT_HOMOLOGA_FECHAS  (Index) 
--
CREATE UNIQUE INDEX CUPADM.CUP_PK_BIT_HOMOLOGA_FECHAS ON CUPADM.CUP_BIT_HOMOLOGA_FECHAS
(ID_EMISION_SF)
LOGGING
TABLESPACE CUP_DATA01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM CUPAPP.CUP_BIT_HOMOLOGA_FECHAS;

--
-- CUP_BIT_HOMOLOGA_FECHAS  (Synonym) 
--
CREATE OR REPLACE SYNONYM CUPAPP.CUP_BIT_HOMOLOGA_FECHAS FOR CUPADM.CUP_BIT_HOMOLOGA_FECHAS;


-- 
-- Non Foreign Key Constraints for Table CUP_BIT_HOMOLOGA_FECHAS 
-- 
ALTER TABLE CUPADM.CUP_BIT_HOMOLOGA_FECHAS ADD (
  CONSTRAINT CUP_PK_BIT_HOMOLOGA_FECHAS
  PRIMARY KEY
  (ID_EMISION_SF)
  USING INDEX CUPADM.CUP_PK_BIT_HOMOLOGA_FECHAS);

-- 
-- Foreign Key Constraints for Table CUP_BIT_HOMOLOGA_FECHAS 
-- 
ALTER TABLE CUPADM.CUP_BIT_HOMOLOGA_FECHAS ADD (
  CONSTRAINT CUP_FK_EMISION_SF 
  FOREIGN KEY (ID_EMISION_SF) 
  REFERENCES CUPADM.EMISION_SF (ID_EMISION_SF),
  CONSTRAINT FK_CAT_ESTATUS_HOMOLOGA 
  FOREIGN KEY (ID_ESTATUS_HOMOLOGA) 
  REFERENCES CUPADM.CAT_ESTATUS_HOMOLOGA (ID_ESTATUS_HOMOLOGA));

GRANT INSERT, SELECT, UPDATE ON CUPADM.CUP_BIT_HOMOLOGA_FECHAS TO CUPAPP;

GRANT INSERT, SELECT, UPDATE ON CUPADM.CUP_BIT_HOMOLOGA_FECHAS TO CUPAPP_ROL;