--INSERT CAT_ESTATUS_HOMOLOGA

SET DEFINE OFF;

Insert into CUPADM.CAT_ESTATUS_HOMOLOGA (ID_ESTATUS_HOMOLOGA, ESTATUS_HOMOLOGA)
 Values (1, 'CUMPLE');
Insert into CUPADM.CAT_ESTATUS_HOMOLOGA (ID_ESTATUS_HOMOLOGA, ESTATUS_HOMOLOGA)
 Values (2, 'HOMOLOGADO');
Insert into CUPADM.CAT_ESTATUS_HOMOLOGA (ID_ESTATUS_HOMOLOGA, ESTATUS_HOMOLOGA)
 Values (3, 'CANCELADO');
COMMIT;
